Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -33,9 +33,16 @@ jobs:
       - name: Build JAR
         run: mvn package -DskipTests
 
+      - name: Check if JAR exists
+        run: |
+          if [ ! -f target/orderapi-0.0.1-SNAPSHOT.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+
   build_and_push_docker:
     runs-on: ubuntu-latest
-    needs: build_and_test  # Asegura que este job se ejecute después del anterior
+    needs: build_and_test
 
     steps:
       - name: Checkout repository
